### ISSUE TITLE
Create jdbc connection class

### ISSUE THREAD

**Issue by sellnat77** [TeamBearsharks/SCRUMProject#1]
Create the jdbc class similar to the one used in the jdbc project

**Comment by sellnat77** [comment]
Basically copy paste the same class that prof gave us but optimize it if possible, add some comments and headers and comment out the actual db connection string info...actually just delete it for the sake of security(github will openly display the password and shizz) so leave that stuff blank

**Comment by Yoh67** [comment]
got it I'll be able to get on this quickly. I'd like to have a chat with you for another matter so let me know when your available so we can chat.

**Comment by sellnat77** [comment]
Ive already started this on a different branch https://github.com/TeamBearsharks/SCRUMProject/tree/jdbcclass
