### ISSUE TITLE
Decide on presentation objects or 1 class

### ISSUE THREAD

**Issue by sellnat77** [TeamBearsharks/SCRUMProject#3]
Should the gui/text presentation be separated into different objects or should we keep everything in one class?

**Comment by Yoh67** [comment]
Could you explain your question? Do we have to have a GUI or can we use Console? If you want one I can take a crack at it.

**Comment by sellnat77** [comment]
I mean, ideally we could go with a gui like jframes and what not, but for the sake of getting it done we should just do it in a similar fashion as the jdbc project
Then if we have time we can probably port it to a gui pretty easily

**Comment by sellnat77** [comment]
Will be working with one class generally speaking
