### ISSUE TITLE
Database object classes?

### ISSUE THREAD

**Issue by sellnat77** [TeamBearsharks/SCRUMProject#5]
Should we create data access objects for each table? 
ie. when running a select for employees, instead of returning the result set, place the result set into an array of employee objects
Ambitious but I think if we have time we should look into implementing this

**Comment by Yoh67** [comment]
I agree so naturally lets get what works up first then implement later if we have time.

**Comment by sellnat77** [comment]
# IT HAS BEEN DECIDED
